---
title: "Prediktivna analiza"
output: html_document
date: "2024-01-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(cowplot)
library(randomForest)
library(tidyverse)
library(stringr)
library(jsonlite)
```

```{r}
collisions2022 <- read_csv("./csv/dft-road-casualty-statistics-collision-2022.csv", show_col_types = F) %>% data.frame(.)
collisions2021 <- read_csv("./csv/dft-road-casualty-statistics-collision-2021.csv", show_col_types = F) %>% data.frame(.)
collisions2020 <- read_csv("./csv/dft-road-casualty-statistics-collision-2020.csv", show_col_types = F) %>% data.frame(.)

collisions <- reduce(list(collisions2022, collisions2021, collisions2020), rbind)

collisions <- filter(collisions, police_force %in% c(1, 48))

collisions <- select(collisions, accident_index, accident_year, longitude, latitude, accident_severity, number_of_vehicles, number_of_casualties, date, day_of_week, time, road_type, speed_limit, light_conditions, weather_conditions, road_surface_conditions, did_police_officer_attend_scene_of_accident)

collisions
```

```{r}
collisions$month <- format(as.Date(collisions$date, format = '%d/%m/%y'), "%m") %>% as.factor(.)
collisions$time <- as.POSIXct(collisions$time, format="%H:%M:%S")
collisions$hour <- as.numeric(format(collisions$time, format="%H"))

collisions$day_of_week <- as.factor(collisions$day_of_week)

collisions

```

Metoda za odabir samo onih redaka iz data framea koji se nalaze na traženoj ruti (zasad napravljeno s fiksnim podacima dok se ne spoji React s R-om).
```{r}
data_json_string <- '[
    {
        "lng": -0.10678,
        "lat": 51.51931
    },
    {
        "lng": -0.10684,
        "lat": 51.51952
    },
    {
        "lng": -0.10622,
        "lat": 51.51962
    },
    {
        "lng": -0.10645,
        "lat": 51.51996
    },
    {
        "lng": -0.10683,
        "lat": 51.52043
    },
    {
        "lng": -0.10689,
        "lat": 51.52051
    },
    {
        "lng": -0.10695,
        "lat": 51.52058
    },
    {
        "lng": -0.107,
        "lat": 51.52065
    },
    {
        "lng": -0.10717,
        "lat": 51.52086
    },
    {
        "lng": -0.10709,
        "lat": 51.52088
    },
    {
        "lng": -0.10698,
        "lat": 51.52092
    },
    {
        "lng": -0.10668,
        "lat": 51.52105
    },
    {
        "lng": -0.1066,
        "lat": 51.52108
    },
    {
        "lng": -0.10642,
        "lat": 51.52111
    },
    {
        "lng": -0.10626,
        "lat": 51.52115
    },
    {
        "lng": -0.10592,
        "lat": 51.52044
    },
    {
        "lng": -0.1057,
        "lat": 51.51978
    },
    {
        "lng": -0.10568,
        "lat": 51.51973
    },
    {
        "lng": -0.1056,
        "lat": 51.51947
    },
    {
        "lng": -0.10551,
        "lat": 51.51922
    },
    {
        "lng": -0.1054,
        "lat": 51.51889
    },
    {
        "lng": -0.10537,
        "lat": 51.51879
    },
    {
        "lng": -0.10532,
        "lat": 51.5186
    },
    {
        "lng": -0.1053,
        "lat": 51.51855
    },
    {
        "lng": -0.1053,
        "lat": 51.5185
    },
    {
        "lng": -0.10529,
        "lat": 51.51829
    },
    {
        "lng": -0.10527,
        "lat": 51.51819
    },
    {
        "lng": -0.10525,
        "lat": 51.51811
    },
    {
        "lng": -0.10521,
        "lat": 51.5179
    },
    {
        "lng": -0.10518,
        "lat": 51.51775
    },
    {
        "lng": -0.10516,
        "lat": 51.51767
    },
    {
        "lng": -0.10513,
        "lat": 51.51756
    },
    {
        "lng": -0.10511,
        "lat": 51.51732
    },
    {
        "lng": -0.10509,
        "lat": 51.51727
    },
    {
        "lng": -0.10508,
        "lat": 51.51722
    },
    {
        "lng": -0.10507,
        "lat": 51.51717
    },
    {
        "lng": -0.10504,
        "lat": 51.5171
    },
    {
        "lng": -0.10501,
        "lat": 51.51702
    },
    {
        "lng": -0.105,
        "lat": 51.51694
    },
    {
        "lng": -0.10495,
        "lat": 51.51675
    },
    {
        "lng": -0.10493,
        "lat": 51.51661
    },
    {
        "lng": -0.10491,
        "lat": 51.51654
    },
    {
        "lng": -0.10487,
        "lat": 51.5164
    },
    {
        "lng": -0.10484,
        "lat": 51.51625
    },
    {
        "lng": -0.10482,
        "lat": 51.51617
    },
    {
        "lng": -0.10473,
        "lat": 51.51609
    },
    {
        "lng": -0.10471,
        "lat": 51.51599
    },
    {
        "lng": -0.10467,
        "lat": 51.51586
    },
    {
        "lng": -0.10467,
        "lat": 51.51582
    },
    {
        "lng": -0.10464,
        "lat": 51.51562
    },
    {
        "lng": -0.10455,
        "lat": 51.51528
    },
    {
        "lng": -0.10442,
        "lat": 51.51474
    },
    {
        "lng": -0.1044,
        "lat": 51.51464
    },
    {
        "lng": -0.10435,
        "lat": 51.51441
    },
    {
        "lng": -0.10432,
        "lat": 51.51424
    },
    {
        "lng": -0.1043,
        "lat": 51.51416
    },
    {
        "lng": -0.10436,
        "lat": 51.51416
    },
    {
        "lng": -0.10448,
        "lat": 51.51417
    },
    {
        "lng": -0.1048,
        "lat": 51.51418
    },
    {
        "lng": -0.10491,
        "lat": 51.51418
    },
    {
        "lng": -0.10506,
        "lat": 51.51418
    },
    {
        "lng": -0.10512,
        "lat": 51.51415
    },
    {
        "lng": -0.10517,
        "lat": 51.51415
    },
    {
        "lng": -0.10526,
        "lat": 51.51415
    },
    {
        "lng": -0.10576,
        "lat": 51.51415
    },
    {
        "lng": -0.10589,
        "lat": 51.51416
    },
    {
        "lng": -0.10597,
        "lat": 51.51416
    },
    {
        "lng": -0.10603,
        "lat": 51.5142
    },
    {
        "lng": -0.1061,
        "lat": 51.5142
    },
    {
        "lng": -0.10616,
        "lat": 51.5142
    },
    {
        "lng": -0.10626,
        "lat": 51.5142
    },
    {
        "lng": -0.10637,
        "lat": 51.5142
    },
    {
        "lng": -0.10643,
        "lat": 51.51421
    },
    {
        "lng": -0.10679,
        "lat": 51.51421
    },
    {
        "lng": -0.10695,
        "lat": 51.51422
    },
    {
        "lng": -0.10723,
        "lat": 51.51422
    },
    {
        "lng": -0.10738,
        "lat": 51.51422
    },
    {
        "lng": -0.10746,
        "lat": 51.51422
    },
    {
        "lng": -0.10757,
        "lat": 51.51422
    },
    {
        "lng": -0.10777,
        "lat": 51.51422
    },
    {
        "lng": -0.10785,
        "lat": 51.51422
    },
    {
        "lng": -0.1079,
        "lat": 51.51422
    },
    {
        "lng": -0.10799,
        "lat": 51.51421
    },
    {
        "lng": -0.10804,
        "lat": 51.51421
    },
    {
        "lng": -0.10811,
        "lat": 51.51421
    },
    {
        "lng": -0.10839,
        "lat": 51.5142
    },
    {
        "lng": -0.1085,
        "lat": 51.51419
    },
    {
        "lng": -0.10853,
        "lat": 51.51419
    },
    {
        "lng": -0.10858,
        "lat": 51.51419
    },
    {
        "lng": -0.10863,
        "lat": 51.51419
    },
    {
        "lng": -0.10877,
        "lat": 51.51418
    },
    {
        "lng": -0.10884,
        "lat": 51.51417
    },
    {
        "lng": -0.10898,
        "lat": 51.51417
    },
    {
        "lng": -0.10918,
        "lat": 51.51416
    },
    {
        "lng": -0.1093,
        "lat": 51.51415
    },
    {
        "lng": -0.10945,
        "lat": 51.51414
    },
    {
        "lng": -0.10973,
        "lat": 51.51408
    },
    {
        "lng": -0.10986,
        "lat": 51.51405
    },
    {
        "lng": -0.10993,
        "lat": 51.51404
    },
    {
        "lng": -0.10999,
        "lat": 51.51403
    },
    {
        "lng": -0.11011,
        "lat": 51.514
    },
    {
        "lng": -0.11017,
        "lat": 51.51399
    },
    {
        "lng": -0.11039,
        "lat": 51.51394
    },
    {
        "lng": -0.11066,
        "lat": 51.51389
    },
    {
        "lng": -0.11085,
        "lat": 51.51385
    },
    {
        "lng": -0.11093,
        "lat": 51.51384
    },
    {
        "lng": -0.11099,
        "lat": 51.51384
    },
    {
        "lng": -0.11104,
        "lat": 51.51383
    },
    {
        "lng": -0.11109,
        "lat": 51.51382
    },
    {
        "lng": -0.11124,
        "lat": 51.5138
    },
    {
        "lng": -0.11135,
        "lat": 51.51378
    },
    {
        "lng": -0.11154,
        "lat": 51.51376
    },
    {
        "lng": -0.11159,
        "lat": 51.51375
    },
    {
        "lng": -0.11165,
        "lat": 51.51374
    },
    {
        "lng": -0.11189,
        "lat": 51.51369
    },
    {
        "lng": -0.11195,
        "lat": 51.51368
    },
    {
        "lng": -0.11202,
        "lat": 51.51366
    },
    {
        "lng": -0.11225,
        "lat": 51.51362
    },
    {
        "lng": -0.11239,
        "lat": 51.51355
    },
    {
        "lng": -0.11245,
        "lat": 51.51352
    },
    {
        "lng": -0.11253,
        "lat": 51.5135
    },
    {
        "lng": -0.11273,
        "lat": 51.51345
    },
    {
        "lng": -0.11308,
        "lat": 51.51332
    },
    {
        "lng": -0.11318,
        "lat": 51.51328
    },
    {
        "lng": -0.1132,
        "lat": 51.51327
    },
    {
        "lng": -0.11325,
        "lat": 51.51325
    },
    {
        "lng": -0.1133,
        "lat": 51.51321
    },
    {
        "lng": -0.11333,
        "lat": 51.51319
    },
    {
        "lng": -0.11336,
        "lat": 51.51317
    },
    {
        "lng": -0.11355,
        "lat": 51.51303
    },
    {
        "lng": -0.11358,
        "lat": 51.513
    },
    {
        "lng": -0.11362,
        "lat": 51.51299
    },
    {
        "lng": -0.11378,
        "lat": 51.51295
    },
    {
        "lng": -0.1141,
        "lat": 51.51288
    },
    {
        "lng": -0.11429,
        "lat": 51.51285
    },
    {
        "lng": -0.11441,
        "lat": 51.51281
    },
    {
        "lng": -0.11456,
        "lat": 51.51278
    },
    {
        "lng": -0.11468,
        "lat": 51.51287
    },
    {
        "lng": -0.11476,
        "lat": 51.51292
    },
    {
        "lng": -0.11486,
        "lat": 51.51297
    },
    {
        "lng": -0.11498,
        "lat": 51.51301
    },
    {
        "lng": -0.11544,
        "lat": 51.51316
    },
    {
        "lng": -0.11567,
        "lat": 51.51322
    },
    {
        "lng": -0.11586,
        "lat": 51.51326
    },
    {
        "lng": -0.11602,
        "lat": 51.51328
    },
    {
        "lng": -0.11635,
        "lat": 51.5133
    },
    {
        "lng": -0.1166,
        "lat": 51.51331
    },
    {
        "lng": -0.11669,
        "lat": 51.5133
    },
    {
        "lng": -0.11698,
        "lat": 51.51328
    },
    {
        "lng": -0.11731,
        "lat": 51.51321
    },
    {
        "lng": -0.1174,
        "lat": 51.51319
    },
    {
        "lng": -0.11761,
        "lat": 51.51314
    },
    {
        "lng": -0.11767,
        "lat": 51.51311
    },
    {
        "lng": -0.11774,
        "lat": 51.51309
    },
    {
        "lng": -0.11779,
        "lat": 51.51308
    },
    {
        "lng": -0.1179,
        "lat": 51.51304
    },
    {
        "lng": -0.11813,
        "lat": 51.51293
    },
    {
        "lng": -0.11827,
        "lat": 51.51286
    },
    {
        "lng": -0.11838,
        "lat": 51.51279
    },
    {
        "lng": -0.11865,
        "lat": 51.51257
    },
    {
        "lng": -0.11879,
        "lat": 51.51241
    },
    {
        "lng": -0.11874,
        "lat": 51.5124
    },
    {
        "lng": -0.11819,
        "lat": 51.51225
    },
    {
        "lng": -0.11797,
        "lat": 51.51218
    },
    {
        "lng": -0.11796,
        "lat": 51.51218
    }
]'

final_data <- fromJSON(data_json_string, flatten = TRUE)
```

```{r}

getMatchingCoordinates <- function(data, collisions) {
  matching_rows <- apply(collisions, 1, function(coll) {
    any(apply(data, 1, function(row) {
      all(round(as.numeric(coll[c('longitude', 'latitude')]), 3) == round(row[c('lng', 'lat')], 3))
    }))
  })

  matches <- collisions[matching_rows, ]
  return(matches)
}
newDF <- getMatchingCoordinates(final_data, collisions)
newDF
```

```{r}

getCoordinates <- function(collisions){
  curr_hour <- format(Sys.time(), "%H")
  curr_weekday <- weekdays(Sys.Date())

  if(curr_weekday == "Sunday"){
    curr_weekday <- 1
  } else if(curr_weekday == "Monday"){
    curr_weekday <- 2
  } else if(curr_weekday == "Tuesday"){
    curr_weekday <- 3
  } else if(curr_weekday == "Wednesday"){
    curr_weekday <- 4
  } else if(curr_weekday == "Thursday"){
    curr_weekday <- 5
  } else if(curr_weekday == "Friday"){
    curr_weekday <- 6
  } else{
    curr_weekday <- 7
  }

  collisions_filtered <- collisions[format(collisions$time, "%H") == curr_hour & collisions$day_of_week == curr_weekday, ]
  return(collisions_filtered)
}

filteredDF <- getCoordinates(collisions)
filteredDF

```